version: "3.8"

services:
  mosquitto:
    image: eclipse-mosquitto
    volumes:
      - ./docker/mosquitto/config:/mosquitto/config
      - ./docker/mosquitto/log:/mosquitto/log
      - ./docker/mosquitto/data:/mosquitto/data
    ports:
      - 1883:1883
      - 9001:9001

  backend:
    image: registry.texhome.lan/raspi-home-backend:main
    environment:
      - GPIOZERO_PIN_FACTORY=mock
      - TAPO_MANAGEMENT=mock
      - TZ=Europe/Rome
    volumes:
      - ./docker/backend/.env:/opt/raspi-home/.env
      - ./docker/backend/.env.local:/opt/raspi-home/.env.local
    ports:
      - 5000:5000

  alexa:
    image: registry.texhome.lan/raspi-home-alexa:main
    volumes:
      - ./docker/alexa/.env.local:/opt/raspi-alexa/.env.local
    ports:
      - 3000:3000

  webapp:
    image: registry.texhome.lan/raspi-home-ionic:main
    environment:
      - SERVER_NAME="app.texhome.lan"
      - BACKEND_URL="http://backend:5000"
      - MOSQUITTO_URL="http://mosquitto:9001"
    ports:
      - 18080:80


