version: "3.8"

services:
  mosquitto:
    image: eclipse-mosquitto
    volumes:
      - ./docker/mosquitto/config:/mosquitto/config
      - ./docker/mosquitto/log:/mosquitto/log
      - ./docker/mosquitto/data:/mosquitto/data
    ports:
      - 1883:1883
      - 9001:9001

  backend:
    image: synology-nas.home:5555/raspi-home-backend:latest
    environment:
      - GPIOZERO_PIN_FACTORY=mock
    volumes:
      - ./docker/backend/.env.local:/opt/raspi-home/.env.local
    ports:
      - 5000:5000

  webapp:
    image: synology-nas.home:5555/raspi-home-ionic:latest
    ports:
      - 18080:80


